$ function declared with vazio returning


def func():int {
  var int a = 10;
  retorna a;

  def inner_func():vazio {
    var int a = 10;
    retorna a; $ expect error
  }

}
