Erro na linha 22: o identificador 'get_contador' não é uma referência válida.